// lib/ui/screens.dart — every screen, routed by sim.phase. Screens render only
// from controller.state() and never poke sim internals. Layout is portrait,
// one-thumb: the primary action lives in the bottom zone on every screen.
import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/semantics.dart' show SemanticsService;
import 'package:flutter/services.dart' show Clipboard, ClipboardData;
import '../audio/audio_service.dart';
import '../data/achievements.dart';
import '../data/boons.dart';
import '../data/characters.dart';
import '../data/enemies.dart';
import '../data/dice.dart';
import '../data/events.dart';
import '../data/mutators.dart';
import '../data/news.dart';
import '../data/relics.dart';
import '../data/themes.dart';
import '../game/controller.dart';
import '../game/daily_share.dart';
import '../game/run_trace.dart';
import '../game/seed_input.dart';
import '../game/tips.dart';
import '../game/trials.dart';
import '../game/weekly.dart';
import '../meta/forge.dart';
import '../meta/play_games_service.dart';
import '../sim/assignment.dart';
import '../sim/keystones.dart';
import '../sim/run_dice.dart';
import 'forge_sheet.dart';
import 'art.dart';
import 'build_identity.dart';
import 'fx.dart';
import 'haptics.dart';
import 'ledger_screen.dart';
import 'logo.dart';
import 'settings_screen.dart';
import 'sprites.dart';
import 'temper_sheet.dart';
import 'theme.dart';
import 'weapons.dart';
import 'widgets.dart';

part 'screens/game_root.dart';
part 'screens/title_screen.dart';
part 'screens/boon_screen.dart';
part 'screens/character_screen.dart';
part 'screens/map_screen.dart';
part 'screens/combat_screen.dart';
part 'screens/combat/hud.dart';
part 'screens/combat/fx.dart';
part 'screens/combat/badges.dart';
part 'screens/combat/enemy_panel.dart';
part 'screens/combat/stage.dart';
part 'screens/combat/player_vitals.dart';
part 'screens/combat/tray.dart';
part 'screens/combat/action_zone.dart';
part 'screens/keystone_screen.dart';
part 'screens/reward_screen.dart';
part 'screens/rest_screen.dart';
part 'screens/shop_screen.dart';
part 'screens/event_screen.dart';
part 'screens/summary_screen.dart';
part 'screens/top_bar.dart';
part 'screens/tutorial_overlay.dart';
