#!/usr/bin/env python3
"""Compile the reviewed source/translation table; --check writes nothing."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name("interface.json")
DEST = ROOT / "lib/l10n/catalog.dart"
LANGS = ("fr", "es", "pt")


def dart(value):
    return json.dumps(value, ensure_ascii=False).replace("$", r"\$")


def render():
    rows = json.loads(SOURCE.read_text())
    for key, values in rows.items():
        assert len(values) == 3 and all(isinstance(v, str) and v for v in values), key
        fields = set(re.findall(r"\{[a-zA-Z]+\}", key))
        assert all(set(re.findall(r"\{[a-zA-Z]+\}", v)) == fields for v in values), key
    lines = ["// Generated by tool/l10n/build_catalog.py. Edit interface.json.",
             "// No runtime file/network lookup. English is the source fallback.",
             "// ignore_for_file: prefer_single_quotes",
             "const interfaceCatalog = <String, Map<String, String>>{"]
    for index, lang in enumerate(LANGS):
        lines.append(f'  "{lang}": {{')
        lines += [f"    {dart(key)}: {dart(values[index])}," for key, values in rows.items()]
        lines.append("  },")
    lines.append("};")
    return "\n".join(lines) + "\n", len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    value, count = render()
    if args.check:
        assert DEST.read_text() == value, "catalog differs; regenerate from its source"
    else:
        DEST.write_text(value)
    print(f"VERIFIED {count} messages x 3 locales; placeholder/key parity; offline catalog")


if __name__ == "__main__":
    main()
