// PlayerComponent: draws PlayerCore state. NO gameplay logic here — the core
// (via the session) owns movement/combat; this picks animation strips, flips
// by facing, and blinks during i-frames.
import 'dart:ui' as ui;

import 'package:flame/components.dart';
import 'package:flame/sprite.dart';

import '../ember_game.dart';
import '../player/player_core.dart';
import '../tuning.dart';

class PlayerComponent extends PositionComponent
    with HasGameReference<EmberGame> {
  PlayerComponent() : super(priority: 3);

  late final Map<PlayerState, SpriteAnimation> _anims;
  late final List<SpriteAnimation> _attacks; // by comboIndex
  SpriteAnimation? _current;
  SpriteAnimationTicker? _ticker;
  double _blinkClock = 0;
  // AKP-3a/3d juice clocks, driven by the game's player-event loop.
  double _squashT = 0; // landing squash-and-stretch remaining
  double _hurtFlashT = 0; // white/red hurt flash remaining

  /// AKP-3a: landing squash. Called on PlayerEvent.landed — AK's landings read
  /// heavy because the sprite compresses for a couple of frames.
  void squash() => _squashT = kLandSquashTime;

  /// AKP-3d: the sprite flashes on the frame damage lands. Without it the
  /// i-frame blink is the only feedback, which reads as "I went invisible".
  void hurtFlash() => _hurtFlashT = kPlayerHurtFlash;

  // Scratch vectors reused every frame (Sprite.render copies them into its
  // own temps; it never keeps the reference) — no per-frame allocations.
  static final _drawPos = Vector2.zero();
  static final _drawSize = Vector2.zero();

  // Hurt flash: hot white-red wash over the sprite silhouette.
  static final _hurtPaint = ui.Paint()
    ..filterQuality = ui.FilterQuality.none
    ..colorFilter = const ui.ColorFilter.mode(
        ui.Color(0xFFFF6B5A), ui.BlendMode.srcATop);

  /// Sheet path for the equipped skin. 'red' (starter) = the base sheets;
  /// other catalog skins are recolors generated by tool/build_skins.py.
  /// Falls back to the base sheet if a skin file is missing, so a catalog
  /// entry without art can never crash a run.
  Future<ui.Image> _sheet(String name) async {
    final skin = game.session.loadout.skinId;
    if (skin != 'red') {
      try {
        return await game.images.load('player/skins/$skin/$name.png');
      } catch (_) {/* fall through to base */}
    }
    return game.images.load('player/$name.png');
  }

  Future<SpriteAnimation> _load(
      String name, int frames, Vector2 size, double stepTime,
      {bool loop = true}) async {
    return SpriteAnimation.fromFrameData(
      await _sheet(name),
      SpriteAnimationData.sequenced(
          amount: frames, stepTime: stepTime, textureSize: size, loop: loop),
    );
  }

  @override
  Future<void> onLoad() async {
    final s22 = Vector2(22, 24);
    final s40 = Vector2(40, 30);
    _anims = {
      PlayerState.idle: await _load('idle', 5, s22, 0.12),
      PlayerState.run: await _load('run', 6, s22, 0.09),
      PlayerState.jump: await _load('jump', 4, s22, 0.08, loop: false),
      PlayerState.fall: await _load('fall', 4, s22, 0.08, loop: false),
      PlayerState.roll:
          await _load('roll', 11, s22, kRollDuration / 11, loop: false),
      PlayerState.hurt: await _load('hit', 6, s22, 0.05, loop: false),
      PlayerState.dead: await _load('hit', 6, s22, 0.05, loop: false),
    };
    _attacks = [
      await _load('attack1', 10, s40, kAttackDuration / 10, loop: false),
      await _load('attack2', 12, s40, kAttackDuration / 12, loop: false),
      await _load('attack3', 8, s40, kAttackDuration / 8, loop: false),
    ];
    _setAnim(_anims[PlayerState.idle]!);
  }

  void _setAnim(SpriteAnimation anim) {
    if (identical(anim, _current)) return;
    _current = anim;
    _ticker = anim.createTicker();
  }

  @override
  void update(double dt) {
    final core = game.session.player;
    _blinkClock += dt;
    if (_squashT > 0) _squashT -= dt;
    if (_hurtFlashT > 0) _hurtFlashT -= dt;
    if (core.state == PlayerState.attack) {
      _setAnim(_attacks[core.comboIndex.clamp(0, _attacks.length - 1)]);
    } else {
      _setAnim(_anims[core.state]!);
    }
    _ticker?.update(dt);
  }

  @override
  void render(ui.Canvas canvas) {
    final core = game.session.player;
    final ticker = _ticker;
    if (ticker == null) return;
    // Blink during i-frames (skip every other 0.08s window).
    if (core.iFrames > 0 &&
        !core.isDead &&
        (_blinkClock / 0.08).floor().isEven) {
      return;
    }
    final sprite = ticker.getSprite();
    final w = sprite.srcSize.x, h = sprite.srcSize.y;
    // Anchor the frame bottom-center on the body's bottom-center.
    final b = core.body;
    canvas.save();
    if (core.facing < 0) {
      canvas.translate(b.centerX * 2, 0);
      canvas.scale(-1, 1);
    }
    // AKP-3a: squash about the feet, easing back to 1:1 over the window.
    if (_squashT > 0) {
      final k = (_squashT / kLandSquashTime).clamp(0.0, 1.0);
      final sx = 1 + (kLandSquashScaleX - 1) * k;
      final sy = 1 + (kLandSquashScaleY - 1) * k;
      canvas.translate(b.centerX, b.bottom);
      canvas.scale(sx, sy);
      canvas.translate(-b.centerX, -b.bottom);
    }
    _drawPos.setValues(b.centerX - w / 2, b.bottom - h);
    _drawSize.setValues(w, h);
    sprite.render(canvas,
        position: _drawPos,
        size: _drawSize,
        overridePaint: _hurtFlashT > 0 ? _hurtPaint : null);
    canvas.restore();
  }
}
