#!/usr/bin/env python3
"""Emit static Dart rig definitions from explicit, reviewed native anatomy.

No runtime JSON or inferred/copy-from-expected anchors. The public art builder
calls this in write/check mode so source art, hand metadata and rigs reproduce.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tool/art/roster_rigs.json"
DEST = ROOT / "lib/ui/combat_roster.g.dart"
JOINTS = ("hip", "neck", "shoulder", "elbow", "wrist", "rearFoot", "frontFoot")
LIMITS = ("legTop", "legSplit", "footTop", "capeLeft")
REGIONS = ("handRect", "forearmRect", "upperArmRect")


def definitions():
    return {k: v for k, v in json.loads(SOURCE.read_text()).items()
            if not k.startswith("_")}


def render(data):
    lines = [
        "// GENERATED by tool/art/build_roster_rigs.py; edit roster_rigs.json.",
        "// Native-pixel anatomy, not runtime inference or a generic recolour rig.",
        "part of 'combat_articulation.dart';",
        "",
        "const _rosterRigs = <String, CombatRig>{",
    ]
    for name, d in data.items():
        assert set(d) == set(JOINTS + LIMITS + REGIONS), name
        lines += [f"  '{name}': CombatRig(", f"    id: '{name}',"]
        for key in JOINTS:
            x, y = d[key]
            assert 0 < x < 32 and 0 < y < 40, (name, key)
            lines.append(f"    {key}: Offset({x}, {y}),")
        lines.append("    cutout: RigCutout(")
        for key in LIMITS:
            lines.append(f"      {key}: {d[key]},")
        for key in REGIONS:
            left, top, right, bottom = d[key]
            assert 0 <= left < right <= 32 and 0 <= top < bottom <= 40, (name, key)
            lines.append(f"      {key}: Rect.fromLTRB({left}, {top}, {right}, {bottom}),")
        lines += ["    ),", "  ),"]
    lines += ["};", ""]
    return "\n".join(lines)


def build(check=False):
    data = definitions()
    source_groups = ROOT / "tool/art/roster-redesign-2026-09-18"
    expected = {
        name for path in source_groups.glob("group-*/source.json")
        for name in json.loads(path.read_text())["characters"]
    }
    assert len(data) == 20 and set(data) == expected, "rig/source roster mismatch"
    hands = json.loads((ROOT / "tool/art/hand_anchors.json").read_text())
    for name, d in data.items():
        assert hands[name] == [d["wrist"][0] / 32, d["wrist"][1] / 40], name
    text = render(data)
    if check:
        assert DEST.read_text() == text, "generated rig data differs"
    else:
        DEST.write_text(text)
    return len(data)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    print(f"Verified {build(args.check)} authored roster rigs")
